// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irmilyeofdujqdkypcjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlybWlseWVvZmR1anFka3lwY2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODg0OTAsImV4cCI6MjA2NTk2NDQ5MH0.cDIx3pyitwWbU6sGqpUb5_jx3wdKdGSy_0E3A-KKkic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);